// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yisdbhbcnmtfrulxinwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpc2RiaGJjbm10ZnJ1bHhpbndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDU2MjIsImV4cCI6MjA2ODUyMTYyMn0.aluz9APowBaUOHOsT-ifVnP6r8p5K7ib7QzHCvS_oNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});